language: scala

scala:
  - 2.11.11

services:
  - mongodb
  - docker

before_install:
  - sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  - sudo apt-get update
  - sudo apt-get -y install netcat unzip apt-transport-https kubectl
  - sudo curl -sSL https://dl.google.com/dl/cloudsdk/channels/rapid/install_google_cloud_sdk.bash --output install.bash
  - sudo chmod +x install.bash
  - ./install.bash --disable-prompts
  - export PATH=$PATH:/root/google-cloud-sdk/bin

env:
  - CONTAINER_TAG="gcr.io/$GC_PROJECT_NAME/device_log_ingestion_service-1.0:T$RAVIS_COMMIT"

addons:
  apt:
    update: true

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - sbt unit
    - name: "Integration Tests"
      script:
        - sbt coverage unit integration
        - sbt coverageReport